version: "3.8"
services:
  downloader-mp3:
    restart: always
    build: 
      context: .
      dockerfile: dockerfile
    ports:
      - 8004:3000
    command: "npm run start"
    environment:
      - PORT=3000